//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunTablo
    {
        public int UrunId { get; set; }
        public string UrunAd { get; set; }
        public string UrunMarka { get; set; }
        public decimal UrunFiyat { get; set; }
        public int UrunAdet { get; set; }
    }
}
